// Generated by CoffeeScript 1.4.0
(function() {
  var ClockBar, CounterBar, TimerBar,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  console.log("hello world");

  Class(Bar({
    constructor: function(key) {
      this.key = key;
    },
    data: function() {},
    progress: function() {},
    enter: function() {},
    update: function() {},
    edit: function() {}
  }));

  ClockBar = (function(_super) {

    __extends(ClockBar, _super);

    function ClockBar() {}

    return ClockBar;

  })(Bar);

  TimerBar = (function(_super) {

    __extends(TimerBar, _super);

    function TimerBar() {}

    return TimerBar;

  })(Bar);

  CounterBar = (function(_super) {

    __extends(CounterBar, _super);

    function CounterBar() {}

    return CounterBar;

  })(Bar);

}).call(this);
